# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: magna.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'magna.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmagna.proto\x12\x05magna\"O\n\x10InferenceRequest\x12\'\n\x06inputs\x18\x01 \x03(\x0b\x32\x17.magna.InferInputTensor\x12\x12\n\nmodel_name\x18\x02 \x01(\t\"S\n\x10InferInputTensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tatype\x18\x02 \x01(\t\x12\r\n\x05shape\x18\x03 \x03(\x03\x12\x10\n\x08raw_data\x18\x04 \x01(\x0c\"Y\n\x11InferenceResponse\x12)\n\x07outputs\x18\x01 \x03(\x0b\x32\x18.magna.InferOutputTensor\x12\x19\n\x11inference_time_ms\x18\x02 \x01(\x02\"T\n\x11InferOutputTensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tatype\x18\x02 \x01(\t\x12\r\n\x05shape\x18\x03 \x03(\x03\x12\x10\n\x08raw_data\x18\x04 \x01(\x0c\"\x0f\n\rHealthRequest\"l\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\r\n\x05state\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x03 \x01(\t\x12\x12\n\nmodel_name\x18\x04 \x01(\t\x12\x17\n\x0finference_count\x18\x05 \x01(\x04\x32\x8e\x01\n\x10InferenceService\x12<\n\x05Infer\x12\x17.magna.InferenceRequest\x1a\x18.magna.InferenceResponse\"\x00\x12<\n\x0bHealthCheck\x12\x14.magna.HealthRequest\x1a\x15.magna.HealthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magna_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=22
  _globals['_INFERENCEREQUEST']._serialized_end=101
  _globals['_INFERINPUTTENSOR']._serialized_start=103
  _globals['_INFERINPUTTENSOR']._serialized_end=186
  _globals['_INFERENCERESPONSE']._serialized_start=188
  _globals['_INFERENCERESPONSE']._serialized_end=277
  _globals['_INFEROUTPUTTENSOR']._serialized_start=279
  _globals['_INFEROUTPUTTENSOR']._serialized_end=363
  _globals['_HEALTHREQUEST']._serialized_start=365
  _globals['_HEALTHREQUEST']._serialized_end=380
  _globals['_HEALTHRESPONSE']._serialized_start=382
  _globals['_HEALTHRESPONSE']._serialized_end=490
  _globals['_INFERENCESERVICE']._serialized_start=493
  _globals['_INFERENCESERVICE']._serialized_end=635
# @@protoc_insertion_point(module_scope)
